#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("School.Droid.Resource", IsApplication=true)]

namespace School.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::School.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::School.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int MenuArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int actionBarBackgroundColor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionBarTextColor = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_other = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int app_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int appicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int archive = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bell = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int border = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int configuration2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int contact_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int down = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int drawer_item_states = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int drawer_item_text = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int drawer_shadow_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int drawer_shadow_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int EditText = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int edittext_reminder = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int header = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_drawer_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_drawer_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_menu_white_18dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int IcAdiemthi = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icdiemthi = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Ichocphi = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Iclichhoc = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Iclichthi = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Iclogout = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon_drawer = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icsettings = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int img_flash = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int monoandroidsplash = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int note = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notepad = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pencil = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Progress = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int radio_off = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int radio_on = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int radio_states = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int radio_text = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int radioBtn_group = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int reminder = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int SGU1 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int SguIcon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int signout = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int tag = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int up = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int user = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080019
			public const int RelativeLayou = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int RelativeLayout5 = 2131230743;
			
			// aapt resource value: 0x7f080079
			public const int btDangNhap = 2131230841;
			
			// aapt resource value: 0x7f080093
			public const int btUpdateData = 2131230867;
			
			// aapt resource value: 0x7f08008f
			public const int btnCancel = 2131230863;
			
			// aapt resource value: 0x7f08008e
			public const int btnDel = 2131230862;
			
			// aapt resource value: 0x7f080012
			public const int btnHK_Ke_DT = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int btnHK_Truoc_DT = 2131230737;
			
			// aapt resource value: 0x7f08008d
			public const int btnSave = 2131230861;
			
			// aapt resource value: 0x7f08005f
			public const int btnTuanKe = 2131230815;
			
			// aapt resource value: 0x7f08005e
			public const int btnTuanTruoc = 2131230814;
			
			// aapt resource value: 0x7f080041
			public const int btn_Expand = 2131230785;
			
			// aapt resource value: 0x7f080092
			public const int ckboxAutoUpdateData = 2131230866;
			
			// aapt resource value: 0x7f080090
			public const int ckboxRemindLT = 2131230864;
			
			// aapt resource value: 0x7f080083
			public const int content_frame = 2131230851;
			
			// aapt resource value: 0x7f080082
			public const int drawer_layout = 2131230850;
			
			// aapt resource value: 0x7f08008c
			public const int edtxt_Content = 2131230860;
			
			// aapt resource value: 0x7f08007a
			public const int errorMSG = 2131230842;
			
			// aapt resource value: 0x7f080014
			public const int icon_drawer = 2131230740;
			
			// aapt resource value: 0x7f080071
			public const int imgBell_HK = 2131230833;
			
			// aapt resource value: 0x7f080081
			public const int imgBell_LT = 2131230849;
			
			// aapt resource value: 0x7f08003d
			public const int imgBell_Tuan = 2131230781;
			
			// aapt resource value: 0x7f08005a
			public const int lbl_DenNgay = 2131230810;
			
			// aapt resource value: 0x7f08000b
			public const int lbl_HK_DT = 2131230731;
			
			// aapt resource value: 0x7f08004b
			public const int lbl_HK_LH = 2131230795;
			
			// aapt resource value: 0x7f080057
			public const int lbl_HK_Tuan = 2131230807;
			
			// aapt resource value: 0x7f08000c
			public const int lbl_NH_DT = 2131230732;
			
			// aapt resource value: 0x7f08004c
			public const int lbl_NH_LH = 2131230796;
			
			// aapt resource value: 0x7f080059
			public const int lbl_TuNgay = 2131230809;
			
			// aapt resource value: 0x7f080084
			public const int left_drawer = 2131230852;
			
			// aapt resource value: 0x7f080074
			public const int linear1 = 2131230836;
			
			// aapt resource value: 0x7f08002b
			public const int linear10 = 2131230763;
			
			// aapt resource value: 0x7f080005
			public const int linear11 = 2131230725;
			
			// aapt resource value: 0x7f08007c
			public const int linear2 = 2131230844;
			
			// aapt resource value: 0x7f080022
			public const int linear45 = 2131230754;
			
			// aapt resource value: 0x7f080033
			public const int linear6 = 2131230771;
			
			// aapt resource value: 0x7f080010
			public const int linearBtn_DT = 2131230736;
			
			// aapt resource value: 0x7f08005d
			public const int linearBtn_Tuan = 2131230813;
			
			// aapt resource value: 0x7f08000d
			public const int linearDT_HK = 2131230733;
			
			// aapt resource value: 0x7f080028
			public const int linearHP = 2131230760;
			
			// aapt resource value: 0x7f08004d
			public const int linearLH = 2131230797;
			
			// aapt resource value: 0x7f08003b
			public const int linearLH_Tuan = 2131230779;
			
			// aapt resource value: 0x7f080038
			public const int linearLH_Tuan_Thu = 2131230776;
			
			// aapt resource value: 0x7f080070
			public const int linearRowLH = 2131230832;
			
			// aapt resource value: 0x7f08006e
			public const int linearThu = 2131230830;
			
			// aapt resource value: 0x7f080060
			public const int linearTiet = 2131230816;
			
			// aapt resource value: 0x7f08007e
			public const int linearTime = 2131230846;
			
			// aapt resource value: 0x7f08000a
			public const int linear_HK_DT = 2131230730;
			
			// aapt resource value: 0x7f08004a
			public const int linear_HK_LH = 2131230794;
			
			// aapt resource value: 0x7f080058
			public const int linear_LH_Tuan_ThoiGian = 2131230808;
			
			// aapt resource value: 0x7f080013
			public const int linear_drawerItem = 2131230739;
			
			// aapt resource value: 0x7f080007
			public const int listDT = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int listDT_HK = 2131230735;
			
			// aapt resource value: 0x7f08002d
			public const int listHP = 2131230765;
			
			// aapt resource value: 0x7f080054
			public const int listLH = 2131230804;
			
			// aapt resource value: 0x7f08006f
			public const int listLHTuan = 2131230831;
			
			// aapt resource value: 0x7f08005c
			public const int listLH_Tuan = 2131230812;
			
			// aapt resource value: 0x7f080076
			public const int listLT = 2131230838;
			
			// aapt resource value: 0x7f080091
			public const int proNL = 2131230865;
			
			// aapt resource value: 0x7f080094
			public const int proUpdateData = 2131230868;
			
			// aapt resource value: 0x7f080018
			public const int profile_image = 2131230744;
			
			// aapt resource value: 0x7f080006
			public const int progressDT = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int progressDTHK = 2131230734;
			
			// aapt resource value: 0x7f08002c
			public const int progressHP = 2131230764;
			
			// aapt resource value: 0x7f080053
			public const int progressLH = 2131230803;
			
			// aapt resource value: 0x7f08005b
			public const int progressLHTuan = 2131230811;
			
			// aapt resource value: 0x7f080075
			public const int progressLT = 2131230837;
			
			// aapt resource value: 0x7f080085
			public const int scroll = 2131230853;
			
			// aapt resource value: 0x7f080016
			public const int separator = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int seperator_DT = 2131230728;
			
			// aapt resource value: 0x7f080048
			public const int seperator_HK = 2131230792;
			
			// aapt resource value: 0x7f080055
			public const int seperator_LH = 2131230805;
			
			// aapt resource value: 0x7f080061
			public const int textView1 = 2131230817;
			
			// aapt resource value: 0x7f080069
			public const int textView10 = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int textView12 = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int textView13 = 2131230827;
			
			// aapt resource value: 0x7f08006c
			public const int textView14 = 2131230828;
			
			// aapt resource value: 0x7f08006d
			public const int textView15 = 2131230829;
			
			// aapt resource value: 0x7f080062
			public const int textView2 = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int textView3 = 2131230819;
			
			// aapt resource value: 0x7f080064
			public const int textView4 = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int textView5 = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int textView7 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int textView8 = 2131230823;
			
			// aapt resource value: 0x7f080068
			public const int textView9 = 2131230824;
			
			// aapt resource value: 0x7f080015
			public const int text_drawer = 2131230741;
			
			// aapt resource value: 0x7f080086
			public const int toast_layout = 2131230854;
			
			// aapt resource value: 0x7f080046
			public const int txtCBGD = 2131230790;
			
			// aapt resource value: 0x7f080025
			public const int txtDKT = 2131230757;
			
			// aapt resource value: 0x7f080020
			public const int txtDRL = 2131230752;
			
			// aapt resource value: 0x7f080026
			public const int txtDT = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int txtDTK = 2131230759;
			
			// aapt resource value: 0x7f080089
			public const int txtDateRM = 2131230857;
			
			// aapt resource value: 0x7f08007f
			public const int txtGioBD = 2131230847;
			
			// aapt resource value: 0x7f080021
			public const int txtHeaderDT = 2131230753;
			
			// aapt resource value: 0x7f080073
			public const int txtHocKy = 2131230835;
			
			// aapt resource value: 0x7f080000
			public const int txtHocKyDT = 2131230720;
			
			// aapt resource value: 0x7f08002a
			public const int txtHocKyHP = 2131230762;
			
			// aapt resource value: 0x7f080035
			public const int txtHocPhi = 2131230773;
			
			// aapt resource value: 0x7f080044
			public const int txtMaLop = 2131230788;
			
			// aapt resource value: 0x7f080042
			public const int txtMaMH = 2131230786;
			
			// aapt resource value: 0x7f080036
			public const int txtMienGiam = 2131230774;
			
			// aapt resource value: 0x7f08007d
			public const int txtMonHoc = 2131230845;
			
			// aapt resource value: 0x7f080023
			public const int txtMonHocDT = 2131230755;
			
			// aapt resource value: 0x7f080034
			public const int txtMonHocHP = 2131230772;
			
			// aapt resource value: 0x7f08004e
			public const int txtMonHoc_HK = 2131230798;
			
			// aapt resource value: 0x7f08003c
			public const int txtMon_Tuan = 2131230780;
			
			// aapt resource value: 0x7f080043
			public const int txtNMH = 2131230787;
			
			// aapt resource value: 0x7f08003a
			public const int txtNgay_Tuan = 2131230778;
			
			// aapt resource value: 0x7f080004
			public const int txtNotify_DT = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int txtNotify_DT_HK = 2131230729;
			
			// aapt resource value: 0x7f080029
			public const int txtNotify_HP = 2131230761;
			
			// aapt resource value: 0x7f080056
			public const int txtNotify_LH_Tuan = 2131230806;
			
			// aapt resource value: 0x7f080072
			public const int txtNotify_LT = 2131230834;
			
			// aapt resource value: 0x7f080049
			public const int txtNotify_LT_HK = 2131230793;
			
			// aapt resource value: 0x7f080037
			public const int txtPhaiDong = 2131230775;
			
			// aapt resource value: 0x7f080080
			public const int txtPhongThi = 2131230848;
			
			// aapt resource value: 0x7f080052
			public const int txtPhong_HK = 2131230802;
			
			// aapt resource value: 0x7f080040
			public const int txtPhong_Tuan = 2131230784;
			
			// aapt resource value: 0x7f080045
			public const int txtSoTC = 2131230789;
			
			// aapt resource value: 0x7f080051
			public const int txtSoTiet_HK = 2131230801;
			
			// aapt resource value: 0x7f08003f
			public const int txtSoTiet_Tuan = 2131230783;
			
			// aapt resource value: 0x7f080088
			public const int txtSubjectRM = 2131230856;
			
			// aapt resource value: 0x7f08001c
			public const int txtTB10 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int txtTB4 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int txtTBTL10 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int txtTBTL4 = 2131230751;
			
			// aapt resource value: 0x7f080032
			public const int txtTCN = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int txtTDD = 2131230769;
			
			// aapt resource value: 0x7f08002e
			public const int txtTSTC = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int txtTSTHP = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int txtTTLD = 2131230768;
			
			// aapt resource value: 0x7f08001a
			public const int txtTenSV = 2131230746;
			
			// aapt resource value: 0x7f080047
			public const int txtThoiGian = 2131230791;
			
			// aapt resource value: 0x7f08004f
			public const int txtThu_HK = 2131230799;
			
			// aapt resource value: 0x7f080039
			public const int txtThu_Tuan = 2131230777;
			
			// aapt resource value: 0x7f080024
			public const int txtTiLe = 2131230756;
			
			// aapt resource value: 0x7f080050
			public const int txtTietBD_HK = 2131230800;
			
			// aapt resource value: 0x7f08003e
			public const int txtTietBD_Tuan = 2131230782;
			
			// aapt resource value: 0x7f08008a
			public const int txtTimeRM = 2131230858;
			
			// aapt resource value: 0x7f080087
			public const int txtTitleRM = 2131230855;
			
			// aapt resource value: 0x7f08007b
			public const int txtVersion_Log = 2131230843;
			
			// aapt resource value: 0x7f080096
			public const int txtVersion_Set = 2131230870;
			
			// aapt resource value: 0x7f080001
			public const int txt_d1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int txt_d2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int txt_d3 = 2131230723;
			
			// aapt resource value: 0x7f08008b
			public const int txt_minutes = 2131230859;
			
			// aapt resource value: 0x7f08001b
			public const int txtmasv = 2131230747;
			
			// aapt resource value: 0x7f080078
			public const int txtmk = 2131230840;
			
			// aapt resource value: 0x7f080077
			public const int txtmsv = 2131230839;
			
			// aapt resource value: 0x7f080095
			public const int txtresult = 2131230869;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DiemThi = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DiemThi_HK = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int drawer_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DrawerHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DTFooter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DTHeader = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DTRow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HocPhi = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int HocPhiFooter = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int HocPhiRow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LHTuanHeader = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LHTuanRow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LichHoc_HK = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LichHoc_Tuan = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LichHocHeader = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LichHocRow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LichThi = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int LogIn = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int LTRow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Menu = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Reminder_Dialog = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Settings = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int DrawerClose = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int DrawerOpen = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int action_websearch = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int Button = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int Mono_Android_Theme_Splash = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int MyTheme_ActionBarStyle = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int Row = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int RowHeader = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int Theme_Splash = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
